### ISSUE TITLE
Little contrast on bottom tooltip

### ISSUE THREAD

**Issue by m-aciek** [mturlo/intellij-spacegray#10]
Screenshot is from Spacegray 1.4.0 on Ubuntu 19.04.
![Zrzut ekranu z 2019-07-27 14-11-39](https://user-images.githubusercontent.com/9288014/61994435-7790fc80-b07a-11e9-9618-76501bf75a2b.png)

**Comment by mturlo** [comment]
Hmm I _think_ it may have been caused by the style change in #7. Will have to figure out a way to style these popups in a non conflicting way (currently parameter info has dark background, this one has light).
