### ISSUE TITLE
[Freature-request] Spacegray Light

### ISSUE THREAD

**Issue by atahrijouti** [mturlo/intellij-spacegray#12]
Can we please have Spacegray Light? 😄 

![image](https://user-images.githubusercontent.com/302837/63586329-6071fb80-c5a1-11e9-94a5-e9088c4e4e6b.png)

As a side note, and this is probably not the right place to ask, I am also curious to how you are making the color-scheme. I mean I know I could just go to the settings and start doing it one by one, but what is your workflow and how do you make sure you are consistent int he color scheme making and so on?

**Comment by mturlo** [comment]
Yeah I remembered the original theme had a light variant as well, just never felt the drive to port it, as I'm mainly used to dark environments myself. But hey, sounds like an excellent idea for a 2.0 :)

**Comment by mturlo** [comment]
As for your side note - I think for a casual project like this, it's as good a place to ask as any.

I've been using the color scheme (the editor part alone, without all of the UI) personally for quite a long time now, so it wasn't a concentrated "I am building a thing" effort. Rather an evolutionary, incremental work I was doing bit by bit whenever I felt like it. That being said, as the original Spacegray is following the base16 design principles (the scheme is basically base16-ocean extended), a good place to start was reading the Styling Guidelines at Chris Kempson's [base16 page](http://chriskempson.com/projects/base16/). Also remember I wasn't _designing_ a theme, merely porting it, so it was more of an engineering work to apply the colours in the right places. 

For the UI part, the hardest thing was (and still is) knowing which labels apply to which elements. When IntelliJ 2019.1 was announced and with it the first 3 "official" themes by [Olga Berdnikova](https://github.com/OlyaB), the way I was working was using a color picker tool ([ColorSlurp](http://colorslurp.com/) for OSX) and then finding the color codes in the theme's source code. Having sources for a working theme was also very helpful to quickly establish a working project and theme definition structure.

**Comment by atahrijouti** [comment]
Oh nice! I am currently using her Cyan Light color scheme as I have noticed I am no longer fond of dark color schemes. I will look into  the code and see if I can play around with it.

thank you very much for your answer!

**Comment by mturlo** [comment]
Hey actually, I've found my old work already started on the light variant editor color scheme - I've pushed it to a branch [here](https://github.com/mturlo/intellij-spacegray/blob/theme/spacegray-light/resources/themes/Spacegray-light.xml). Feel free to play with it if you like - needless to say, PRs are very welcome :)
