### ISSUE TITLE
Color scheme does not work for python in pycharm 2019.3

### ISSUE THREAD

**Issue by shijy07** [mturlo/intellij-spacegray#13]
![image](https://user-images.githubusercontent.com/3454697/70791897-eaaabf00-1d4c-11ea-9bb4-399fb52f7bae.png)

**Comment by mturlo** [comment]
Hmm, weird. I'm not a Python user primarily, so naturally not all edge cases will be covered, but in your screenshot the keyword colour looks like default for Darcula and the theme specifies them to be overriden in:
https://github.com/mturlo/intellij-spacegray/blob/9813346898d3c2b8dd23a1725e1aee56ea34a4f9/resources/themes/Spacegray.xml#L249
and then:
https://github.com/mturlo/intellij-spacegray/blob/9813346898d3c2b8dd23a1725e1aee56ea34a4f9/resources/themes/Spacegray.xml#L148-L152
Maybe you're overriding these settings in your IDE Color Scheme section?
