### ISSUE TITLE
Underlined Selected Tab not working

### ISSUE THREAD

**Issue by aacoakley** [mturlo/intellij-spacegray#17]
Spacegray
<img width="464" alt="image" src="https://user-images.githubusercontent.com/39567133/165575904-955cedda-715d-4caf-8e67-3fcca8c64b26.png">
vs Darcula
<img width="468" alt="image" src="https://user-images.githubusercontent.com/39567133/165575625-aae16d9e-4e68-49b9-b366-53a52a02effd.png">

The underlined selector is super useful for me personally.

**Comment by mturlo** [comment]
Yeah tbh I also struggle to tell, which tab is active at a given moment - need to do something about it.

I could do a 1px underline like so
![image](https://user-images.githubusercontent.com/2657242/165739655-284c7dae-e811-4469-8273-2e4cec0e893a.png)
or 2px like
![image](https://user-images.githubusercontent.com/2657242/165739684-a444e3b6-0154-4f36-a247-9c00be7619ac.png)
...but I really like how it's solved in Sublime originally:
![image](https://user-images.githubusercontent.com/2657242/165739767-27ba3c0e-dbfc-4ad3-88b2-1ba9e07cb8a6.png)
Looks super clean to me - and I _think_ that's how it used to work originally in the IntelliJ theme as well. Thing is, I've found close to no documentation on themes on IntelliJ's side and any new version of the IDE the rules change or stop working altogether, so it's possible that's what happened.

**Comment by aacoakley** [comment]
I really struggle to tell what is highlighted in Intellij without that little underline nowadays. I even tried making the Selected Tab change to black, which works well enough until I switch to a tab that has coloring specific to scope. I really dig the 2px underline, if you want my opinion.

**Comment by mturlo** [comment]
Just submitted v 1.5.0 for approval - should be available soon.

**Comment by aacoakley** [comment]
That's awesome. Thanks!
