### ISSUE TITLE
Suggestion: add screenshots to JetBrains plugin's page.

### ISSUE THREAD

**Issue by m-aciek** [mturlo/intellij-spacegray#2]
IMHO adding them [there](https://plugins.jetbrains.com/plugin/12122-spacegray-theme) would boost the download rate.

**Comment by m-aciek** [comment]
@mturlo Also you could link the plugin page from this GitHub repository.

**Comment by mturlo** [comment]
Done and done.

Link to plugin page added in repo description - I may add it later to the README as well (and a screenshot probably, but for now I just want to reduce redundancy in both cases).
