### ISSUE TITLE
Add support for more languages

### ISSUE THREAD

**Issue by mallowigi** [mturlo/intellij-spacegray#6]
I think if you want to be exhaustive you would need to support more languages.

The best way to do so is by adding the relevant plugins (if you have ultimate): Ruby, Scala, Python, PHP, Kotlin, HAML, C, C++, Swift etc.

**Comment by mturlo** [comment]
Thanks for that. I do not, unfortunately, have Ultimate, but I'll try to figure something out (RubyMine Community maybe?). I use IntelliJ almost exclusively for Scala, so Scala support should be the best at the moment - the colour scheme is just an XML export of the one I've been using (and refining) personally for a long time now. At the same time, while defining it, I've tried to use the general language abstractions as much as possible to maintain consistency between languages.

Also - if you're reading this and have any particular grudges/suggestions regarding support for your language of choice, let's have them here. Contributions are, of course, very welcome.

**Comment by atahrijouti** [comment]
FYI: As this is an Open Source project, you can easily request an Ultimate license just for this use-case ;-) heck, you can request all licenses for this specific project

https://www.jetbrains.com/community/opensource/

**Comment by mturlo** [comment]
Ooh, I did _not_ know that - thanks! Anyway, I eventually got the license by participating in the plugin contest :)
