### ISSUE TITLE
Ineligible text in parameter info

### ISSUE THREAD

**Issue by atahrijouti** [mturlo/intellij-spacegray#7]
When calling a function in Kotlin, and I try to get the Parameter Info tooltip with ⌘+P on macOS, I get something like this 
![image](https://user-images.githubusercontent.com/302837/57181514-23b8b200-6e95-11e9-8b0a-c94cb05dc442.png)

But, if I fill in the params using the named arguments way, once I fill in the first argument and press comma, the tooltip becomes intelligible as in the next preview

![image](https://user-images.githubusercontent.com/302837/57181494-d6d4db80-6e94-11e9-8633-b6aaeb2fe59c.png)

For comparison here it is in the default dark theme 

![image](https://user-images.githubusercontent.com/302837/57181585-0506eb00-6e96-11e9-8618-26bd0f7bacdd.png)

I hope this gets fixed :-) Otherwise I love your theme so much !

**Comment by mturlo** [comment]
Hi, Abderrahmane! Thanks for your kind feedback and excellent problem description. Should be an easy fix, once I figure out which colours to change (hopefully without breaking anything).
