### ISSUE TITLE
Active Tab Color in 2019.2

### ISSUE THREAD

**Issue by jjanusch** [mturlo/intellij-spacegray#8]
The active tab color in 2019.2 appears to have changed from being a slightly lighter shade of blue to a much lighter gray color.

Compare 2019.2 (see index.php tab):

![2019.2](https://user-images.githubusercontent.com/3516836/61883877-11587e00-aeb0-11e9-9488-c45e5157b078.png)

to the expected (see LunchbotActor, second tab):

![Expected](https://raw.githubusercontent.com/mturlo/intellij-spacegray/master/screenshots/lunchbot.png)

**Comment by mturlo** [comment]
Yeah, the new version breaks the themes a bit by setting a default colour to some of the components and changing the element labels around. I should put together a fix shortly, as it bothers me personally as well.
